<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\Services\SlugService;
class Page extends Model
{
//    use Sluggable;
//    use Slu
	protected $table    = 'pages';
    protected $fillable = ['parent_id', 'title','slug','content','status','template', 'order'];

     public static function boot()
     {
         parent::boot(); // TODO: Change the autogenerated stub

         static::updating(function($user){
             $user->logs()->attach(Auth::user()->id, ['module_name' => 'User', 'log' => Auth::user()->first_name . ' ' . Auth::user()->last_name . ' is updating ' . $user->name]);
         });

         static::creating(function($user){
             if(Auth::check()){
                 $user->logs()->attach(Auth::user()->id, ['module_name' => 'User', 'log' => Auth::user()->first_name . ' ' . Auth::user()->last_name . ' is creating ' . $user->name]);
             }

         });

         static::deleting(function($user){
             $user->logs()->attach(Auth::user()->id, ['module_name' => 'User', 'log' => Auth::user()->first_name . ' ' . Auth::user()->last_name . ' is deleting ' . $user->name]);
         });
     }

    public function getTemplateFormatAttribute(){
        if($this->template == 'single_column')
        {
            return 'Single Column Template';
        }
        elseif($this->template == 'two_column')
        {
            return 'Two Column Template';
        }
        else{
            return 'Three Column Template';
        }
    }

     public function logs(){
        return $this->belongsToMany(User::class, 'logs', 'module_id')
            ->withTimestamps()
            ->latest('pivot_updated_at');
    }
    public function parent(){
        return $this->belongsTo(Page::class, 'parent_id', 'id');
    }

    public function children(){
        return $this->hasMany(Page::class, 'id', 'parent_id');
    }
//    public function sluggable()
//    {
//        return [
////            'slug'
//            'slug' => [
//                'source' => 'title'
//            ]
//        ];
//    }

}
